services:
  flask:
    container_name: flask
    build: # Using custom Dockerfile, no need image: python:3.8-slim
      context: ./app-server
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app-server:/app
    networks:
      laternet:
        ipv4_address: 10.20.0.2

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx-ci.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
        laternet:
          ipv4_address: 10.20.0.3

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    depends_on:
      - flask
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      laternet:
        ipv4_address: 10.20.0.4

networks:
  laternet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1
