services:
  snort:
    image: snort3-jq
    container_name: snort3
    build:
      context: ./snort3-build
      dockerfile: Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./snort3:/etc/snort
      - ./snort3-log:/root
    command: bash -c "snort -i enX0 --daq-dir /usr/lib/daq -c /etc/snort/snort.lua --lua 'alert_json = {file = true}' -A alert_json & /root/snort3-forwarder.sh"
    restart: unless-stopped