on:
  workflow_run:
    workflows: ["Flask CI for Dev Branches"]
    types:
      - completed

jobs:
  security-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Latergram"
          path: "."
          format: "HTML"
          out: "dependency-check-report"

      - name: Install Safety
        run: pip install safety

      - name: Run Safety Check and Save Report
        run: |
          mkdir -p safety-report
          safety check --full-report --file=requirements.txt > safety-report/safety-report.txt

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: dependency-check-report

      - name: Upload Safety Report
        uses: actions/upload-artifact@v4
        with:
          name: Safety-Report
          path: safety-report
