name: OWASP Dependency Check

on:
  workflow_run:
    workflows: ["Flask CI for Dev Branches"]
    types:
      - completed

jobs:
  python-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: List files for debugging
      #   run: |
      #     echo "Current directory: $(pwd)"
      #     ls -alR

      - name: Install tools
        run: |
          pip install -r app-server/requirements.txt
          pip install safety pip-audit

      - name: Run Safety
        run: safety check

      - name: Run pip-audit
        run: pip-audit