name: Docker + Snort3

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # main-stack:
  #   name: Test Main Stack
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v3

  #   - name: Install Docker Compose
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y docker-compose

  #   - name: Build and Run Main Stack
  #     run: docker-compose -f docker-compose.yml up -d --build

  #   - name: Wait for Services to be Ready
  #     run: sleep 20

  #   - name: Test Flask via NGINX
  #     run: |
  #       curl -s --fail http://localhost:80 || (echo "Flask app failed!" && exit 1)

  #   - name: Teardown
  #     if: always()
  #     run: docker-compose -f docker-compose.yml down -v

  snort3-test:
    name: Snort3 Smoke Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build custom image
      run: docker build -t snort3-jq ./snort3-build
    
    - name: Build Snort3 Container (without host network)
      run: |
        docker compose -f snort-compose.yml config > temp.yml
        sed -i '/network_mode/d' temp.yml  # Remove host networking for CI
        docker compose -f temp.yml up -d --build

    - name: Check Snort3 is Running
      run: docker ps | grep snort3 || (echo "Snort3 failed to run" && exit 1)

    - name: Teardown Snort3
      if: always()
      run: docker compose -f temp.yml down -v
