name: Flask CI for Dev Branches

on:
  push:
    branches:
      - dev-release-*
    paths:
      - 'app-server/**'
  pull_request:
    branches:
      - dev-release-*

jobs:
  flask-docker:
    runs-on: ubuntu-latest
    name: Flask Container Tests

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start Flask Container
      run: docker-compose -f docker-compose.ci.yml up -d --build

    - name: Print Flask container logs (debugging)
      run: docker logs flask || true

    - name: Print MySQL container logs (debugging)
      run: docker logs mysqldb || true

    - name: Show Flask container status
      run: docker ps -a

    - name: Wait for Flask via NGINX (Full Stack Check)
      run: |
        for i in {1..20}; do
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80)
          if [ "$STATUS" = "200" ]; then
            echo "Flask is ready via NGINX (HTTP $STATUS)"
            break
          else
            echo "NGINX not ready yet (HTTP $STATUS)..."
            sleep 5
          fi
        done

    - name: Run Flask Tests in Container
      run: docker exec flask python -m pytest /app/tests

    # This shit too strict LMAO
    # - name: Lint Flask App in Container
    #   run: docker exec flask flake8 /app


    - name: Teardown
      if: always()
      run: docker-compose -f docker-compose.ci.yml down -v
